"""add features to bike table

Revision ID: 080f91297301
Revises: cdcb8cfc26ff
Create Date: 2022-01-25 10:00:16.642280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080f91297301'
down_revision = 'cdcb8cfc26ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('model_id', sa.Integer(), nullable=True))
    op.add_column('bike', sa.Column('condition_id', sa.Integer(), nullable=True))
    op.add_column('bike', sa.Column('frame_size_id', sa.Integer(), nullable=True))
    op.add_column('bike', sa.Column('front_travel', sa.Float(), nullable=False))
    op.add_column('bike', sa.Column('rear_travel', sa.Float(), nullable=False))
    op.drop_constraint('bike_brand_id_fkey', 'bike', type_='foreignkey')
    op.create_foreign_key(None, 'bike', 'frame_size', ['frame_size_id'], ['id'])
    op.create_foreign_key(None, 'bike', 'condition', ['condition_id'], ['id'])
    op.create_foreign_key(None, 'bike', 'model', ['model_id'], ['id'])
    op.drop_column('bike', 'brand_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bike', type_='foreignkey')
    op.drop_constraint(None, 'bike', type_='foreignkey')
    op.drop_constraint(None, 'bike', type_='foreignkey')
    op.create_foreign_key('bike_brand_id_fkey', 'bike', 'brand', ['brand_id'], ['id'])
    op.drop_column('bike', 'rear_travel')
    op.drop_column('bike', 'front_travel')
    op.drop_column('bike', 'frame_size_id')
    op.drop_column('bike', 'condition_id')
    op.drop_column('bike', 'model_id')
    # ### end Alembic commands ###
