"""wheel size table

Revision ID: e730f3c1cc5b
Revises: 5e8e422d2be0
Create Date: 2022-01-16 09:52:55.806101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e730f3c1cc5b'
down_revision = '5e8e422d2be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wheel_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wheel_size')
    # ### end Alembic commands ###
