"""suspension model

Revision ID: ff84ec9f85ae
Revises: f06737b1ecbc
Create Date: 2022-01-24 15:20:01.396280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff84ec9f85ae'
down_revision = 'f06737b1ecbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('REAR', 'FRONT', name='suspensiontype'), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model')
    # ### end Alembic commands ###
